version: "3.7"
services:
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass